lsp:
  server:
    type: docker
    subtype: image
    name: ghcr.io/wurly200a/builder-esp32/esp-idf-v5.5:latest
    server: clangd
    launch_command: >
      /usr/local/bin/clangd-with-idf
      --compile-commands-dir=/workspaces/MidiAppBox/src/build
    launch_parameters: [ "-w", "/workspaces/MidiAppBox" ]
  mappings:
    - source: .
      destination: /workspaces/MidiAppBox
